pipeline:
  build:
    image: golang
    commands:
      - go build
  publish:
    image: plugins/docker
    repo: undeadops/bar
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

