kind: pipeline
name: default

steps:
- name: test
  image: mysql:5
  commands:
  - sleep 15
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
- name: database
  image: mysql:5
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test