kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
    - go build
  
- name: publish 
  image: plugins/docker
  settings:
    repo: undeadops/bar
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

services:
- name: database
  image: mysql:5
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test
